#!/usr/bin/env zsh
set -e
set -x

## Installs service generated by:
## podman run --rm --name jamoo.dev -p 8080:3000 -v $PWD/posts:/website/posts -v $PWD/static:/website/static -v $PWD/templates:/website/templates jamoo.dev
## podman generate systemctl --new -n --files

function make_random_key() {
  readonly tgt_dir="/tmp/website-install/"
  mkdir -p $tgt_dir
  fn=$(mktemp -p $tgt_dir -u)
  ssh-keygen -f $fn -q -P ""
  echo $fn
}

function as_user () {
  readonly user=${1:?"The user must be specified"}
  readonly command="${@:2}"

  # make a key
  priv_key_fn=$(make_random_key)

  # authorize
  auth_keys="/home/$tgt_user/.ssh/authorized_keys"
  sudo mkdir -p "/home/$tgt_user/.ssh"
  if [ ! -f $auth_keys ]; then
    # ensure it exists
    sudo touch $auth_keys
  fi

  sudo cp $auth_keys "${auth_keys}.bak"
  echo $(cat "${priv_key_fn}.pub") | sudo tee -a $auth_keys > /dev/null
  sudo chmod -R u=rwX,g-rwx,o-rwx "/home/$tgt_user/.ssh"
  sudo chown -R ${tgt_user}:${tgt_user} "/home/$tgt_user/.ssh"

  # run command
  ssh -i $priv_key_fn ${tgt_user}@localhost $command

  # cleanup
  sudo mv "${auth_keys}.bak" $auth_keys
  sudo chmod u=rwX,g-rwx,o-rwx $auth_keys
  sudo chown ${tgt_user}:${tgt_user} $auth_keys
  rm $priv_key_fn
}

function move_owner_keep_rights () {
  readonly tgt_user=${1:?"Target user must be specified"}
  readonly tgt_fn=${2:?"Target file must be specified"}
  if [ -d $tgt_fn ]; then
    setfacl -R -m u:${UID}:rwx "$tgt_fn"
  else
    setfacl -m u:${UID}:rw "$tgt_fn"
  fi
  sudo chown ${tgt_user}:${tgt_user} $tgt_fn
}


tgt_user="webuser"
tgt_dir="/home/$tgt_user/.config/systemd/user"
src_fn="container-jamoo.dev.service"

# copy to user directory
if [ ! -d $tgt_dir ]; then
  mkdir -p $tgt_dir
  move_owner_keep_rights $tgt_user "/home/webuser/.cache"
fi
cp -Z $src_fn $tgt_dir
move_owner_keep_rights $tgt_user "$tgt_dir/$src_fn"

# then start at login

as_user $tgt_user systemctl --user enable --now $src_fn
